- backend/server/build.gradle
- backend/server/src/docs/asciidoc/account.adoc
- backend/server/src/main/java/shop/sellution/server/account/application/AccountService.java
- backend/server/src/main/java/shop/sellution/server/account/application/AccountServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/account/domain/Account.java
- backend/server/src/main/java/shop/sellution/server/account/dto/request/CheckAccountReq.java
- backend/server/src/main/java/shop/sellution/server/account/dto/request/UpdateAccountReq.java
- backend/server/src/main/java/shop/sellution/server/account/infrastructure/AccountAuthService.java
- backend/server/src/main/java/shop/sellution/server/account/presentation/AccountAuthController.java
- backend/server/src/main/java/shop/sellution/server/account/presentation/AccountController.java
- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- backend/server/src/main/resources/static/docs/account.html
- backend/server/src/main/resources/static/docs/index.html
- backend/server/src/test/java/shop/sellution/server/account/application/AccountServiceImplTest.java
- backend/server/src/test/java/shop/sellution/server/account/infrastructure/AccountAuthServiceTest.java
- backend/server/src/test/java/shop/sellution/server/account/presentation/AccountAuthControllerTest.java
- backend/server/src/test/java/shop/sellution/server/account/presentation/AccountControllerTest.java
- backend/server/src/test/resources/application.yml
- 계좌 인증 API 테스트 코드 작성 
- 계좌 생성 API, 테스트 코드 작성
- 계좌 수정 API, 테스트 코드 작성
- 계좌 삭제 API, 테스트 코드 작성
계좌 인증 API 테스트 코드   ->  webflux를 쓰는 외부 API 이용하는 API 테스트코드 입니다.
> [K1P-122] back-계좌(결제수단) 관련 API 개발

- backend/server/.idea/compiler.xml
- backend/server/build.gradle
- backend/server/src/main/java/shop/sellution/server/category/application/CustomerCategoryServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/company/application/CompanyDisplaySettingServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/company/application/CompanySaleSettingServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/company/application/CompanyUrlSettingServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/company/domain/MonthOption.java
- backend/server/src/main/java/shop/sellution/server/company/domain/WeekOption.java
- backend/server/src/main/java/shop/sellution/server/company/dto/FindCompanySaleSettingRes.java
- backend/server/src/main/java/shop/sellution/server/company/dto/SaveCompanyDisplaySettingReq.java
- backend/server/src/main/java/shop/sellution/server/company/dto/SaveCompanySaleSettingReq.java
- backend/server/src/main/java/shop/sellution/server/company/dto/SaveCompanyUrlSettingReq.java
- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/product/application/CustomerProductServiceImpl.java
- backend/server/src/test/java/shop/sellution/server/company/application/CompanySaleSettingServiceImplTest.java
- backend/server/src/test/java/shop/sellution/server/company/application/CompanyUrlSettingServiceImplTest.java
- backend/server/src/test/java/shop/sellution/server/company/domain/CompanyRepositoryTest.java
- backend/server/src/test/java/shop/sellution/server/company/presentation/CompanyControllerTest.java
> [K1P-130] back - refactor : 고객 시점 쇼핑몰 관리 api 수정

- backend/server/src/main/java/shop/sellution/server/address/dto/request/SaveAddressReq.java
- frontend/sellution-app/src/shopping/component/mypage/address/AddComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/address/DetailComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/address/ListComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/editSimplePassword/CheckSmsAuthComponent.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/setting/address/AddComponent.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/setting/address/DetailComponent.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/setting/address/ListComponent.jsx
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/OrderComponent.jsx
- frontend/sellution-app/src/shopping/router/ordersheet/setting/address/addressRouter.jsx
- frontend/sellution-app/src/shopping/router/subscriptionDelivery/subscriptionDeliveryRouter.jsx
- 회원 휴대폰 인증 UI
- 회원 주문시 주소 UI
- 회원 주문시 배송지 설정에 아직 추가될 부분이 있지만, OrderComponent가 공통작업이라 먼저 PR 올립니다!
> [K1P-89] front - 회원 주문시 주소 UI, 휴대폰 인증 UI

- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentCancelService.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentService.java
- backend/server/src/main/java/shop/sellution/server/sms/presentation/SmsController.java
- backendPG/pgserver/src/docs/asciidoc/auth.adoc
- backendPG/pgserver/src/docs/asciidoc/index.adoc
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/account/infrastructure/AccountAuthService.java
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/account/infrastructure/IamPortTokenClient.java
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/account/presentation/AccountAuthController.java
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/payment/presentation/PaymentController.java
- backendPG/pgserver/src/main/resources/logback.xml
- backendPG/pgserver/src/test/java/pg/sellution/pgserver/account/infrastructure/AccountAuthServiceTest.java
- backendPG/pgserver/src/test/java/pg/sellution/pgserver/account/presentation/AccountAuthControllerTest.java
- backendPG/pgserver/src/test/java/pg/sellution/pgserver/auth/application/AccessTokenServiceTest.java
- backendPG/pgserver/src/test/java/pg/sellution/pgserver/auth/presentation/AuthControllerTest.java
- backendPG/pgserver/src/test/java/pg/sellution/pgserver/payment/presentation/PaymentControllerTest.java
[K1P-150] 
- PG서버 비동기로직 -> 동기로직 변경 및 테스트코드 수정
[K1P-150]: https://hyosung-kosa-team1.atlassian.net/browse/K1P-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [K1P-150] back- pg서버 로직 코드,테스트 리팩토링

- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
- frontend/sellution-app/src/shopping/component/onetimeDelivery/OrderComponent.jsx
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/OrderComponent.jsx
- frontend/sellution-app/src/shopping/layout/OrderListLayout.jsx
- frontend/sellution-app/src/shopping/layout/order/CouponSelection.jsx
- frontend/sellution-app/src/shopping/layout/order/PaymentEstimation.jsx
- frontend/sellution-app/src/shopping/layout/order/SubscriptionDeliverySetting.jsx
- 주문 페이지 옵션사항 api 연결
- 주문 페이지에서 옵션별로 컴포넌트로 변경
- 주문 페이지 옵션 api 연결
-  결제수단 api 연결 필요
> [K1P-209] FRONT - 주문 페이지 옵션 api 연결

- backend/server/build.gradle
- backend/server/src/main/java/shop/sellution/server/company/application/CompanySaleSettingServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/company/domain/repository/DayOptionRepository.java
- backend/server/src/main/java/shop/sellution/server/company/domain/repository/MonthOptionRepository.java
- backend/server/src/main/java/shop/sellution/server/company/domain/repository/WeekOptionRepository.java
- backend/server/src/main/java/shop/sellution/server/company/dto/FindCompanySaleSettingRes.java
- backend/server/src/main/java/shop/sellution/server/company/dto/FindOptionRes.java
- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- backend/server/src/main/java/shop/sellution/server/product/S3Service.java
- backend/server/src/main/java/shop/sellution/server/product/application/ProductServiceImpl.java
- backend/server/src/main/resources/data.sql
- 배송요일, 배송주기, 정기배송기간  id 값 같이 보내줘야함
> [K1P-103] shoppingmall setting

- backend/server/src/main/java/shop/sellution/server/account/application/AccountService.java
- backend/server/src/main/java/shop/sellution/server/account/application/AccountServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/account/domain/AccountRepository.java
- backend/server/src/main/java/shop/sellution/server/account/dto/request/SaveAccountReq.java
- backend/server/src/main/java/shop/sellution/server/account/dto/response/FindAccountDetailRes.java
- backend/server/src/main/java/shop/sellution/server/account/presentation/AccountController.java
- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentService.java
[K1P-244]
- 계좌 상세 조회 API 추가 
- 계좌 생성후 id 반환
[K1P-244]: https://hyosung-kosa-team1.atlassian.net/browse/K1P-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  [K1P-244] back - 계좌 상세 조회 API 추가 , 계좌 생성후 id 반환

- backend/server/src/main/java/shop/sellution/server/company/application/CompanyDisplaySettingServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- backend/server/src/main/java/shop/sellution/server/product/S3Service.java
- backend/server/src/main/java/shop/sellution/server/product/application/ProductServiceImpl.java
> [K1P-103] back - 회사, 상품 이미지 resizing

- frontend/sellution-app/src/shopping/component/mypage/IndexComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/editSimplePassword/CheckSmsAuthComponent.jsx
> [K1P-199] customer sms - 간편비밀번호 수정 관련 경로 수정

- backend/server/.idea/compiler.xml
- backend/server/src/main/java/shop/sellution/server/address/application/AddressService.java
- backend/server/src/main/java/shop/sellution/server/address/application/AddressServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/address/dto/request/SaveAddressReq.java
- backend/server/src/main/java/shop/sellution/server/address/dto/response/FindAllAddressRes.java
- backend/server/src/main/java/shop/sellution/server/address/presentation/AddressController.java
- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- address 생성시 addressId 값 클라이언트에게 전달
- address 조회할 때 zipcode도 같이 조회
- address 처음 생성시 기본 배송지로 저장
- 기본 배송지 삭제 불가능
> [K1P-89] customer address 

- frontend/sellution-app/src/client/component/idInquiry/SmsAuthComponent.jsx
- frontend/sellution-app/src/client/component/idInquiry/ViewComponent.jsx
- frontend/sellution-app/src/client/component/join/BeginComponent.jsx
- frontend/sellution-app/src/client/component/join/ContractAuthComponent.jsx
- frontend/sellution-app/src/client/component/join/SmsAuthComponent.jsx
- frontend/sellution-app/src/client/component/pwInquiry/ResetComponent.jsx
- frontend/sellution-app/src/client/component/pwInquiry/SmsAuthComponent.jsx
- 고객 아이디 생성 UI
- 고객 아이디 찾기 UI
- 고객 비밀번호 찾기 UI
> [K1P-258] client find id/pwd  - 대신 PR

- backend/server/src/main/java/shop/sellution/server/account/application/AccountServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/account/domain/Account.java
- backend/server/src/main/java/shop/sellution/server/account/domain/AccountRepository.java
- backend/server/src/main/java/shop/sellution/server/event/application/EventServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/event/presentation/EventController.java
- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/order/domain/Order.java
- backend/server/src/main/java/shop/sellution/server/order/dto/response/CountOrderInfoRes.java
- backend/server/src/main/java/shop/sellution/server/order/presentation/OrderController.java
- frontend/sellution-app/src/shopping/component/mypage/editSimplePassword/EditComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/payment/AddComponent.jsx
- frontend/sellution-app/src/shopping/component/onetimeDelivery/OrderCompletedComponent.jsx
- frontend/sellution-app/src/shopping/component/onetimeDelivery/OrderComponent.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/setting/payment/AddComponent.jsx
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/OrderCompletedComponent.jsx
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/OrderComponent.jsx
- frontend/sellution-app/src/shopping/layout/order/DeliverySelection.jsx
- frontend/sellution-app/src/shopping/layout/order/PaymentEstimation.jsx
- frontend/sellution-app/src/shopping/layout/order/PaymentMethodSelection.jsx
- frontend/sellution-app/src/shopping/layout/order/SubscriptionDeliverySetting.jsx
- frontend/sellution-app/src/shopping/store/stores/useAuthStore.js
- frontend/sellution-app/src/shopping/store/stores/useOrderListStore.js
[K1P-244,K1P-239,K1P-266]
- 계좌 중복체크하기위해 해시값 추가 
- 주문 페이지 API연결, 수정
- 결제수단 저장페이지 수정
> [K1P-231,K1P-230] front,back - 계좌 중복체크하기위해 해시값 추가 , 주문 페이지 API연결, 수정, 결제수단 저장페이지 수정

- backend/server/src/main/java/shop/sellution/server/event/application/EventService.java
- backend/server/src/main/java/shop/sellution/server/event/application/EventServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/event/presentation/EventController.java
- frontend/sellution-app/src/client/business/event/useEventAdd.js
- frontend/sellution-app/src/client/business/event/useEventDetail.js
- frontend/sellution-app/src/client/business/event/useEventList.js
- frontend/sellution-app/src/client/component/event/AddComponent.jsx
- frontend/sellution-app/src/client/component/event/DetailComponent.jsx
- frontend/sellution-app/src/client/layout/shopManagement/ShoppingMallPreview.jsx
- frontend/sellution-app/src/client/utility/apis/event/eventAddApi.js
- frontend/sellution-app/src/client/utility/apis/event/eventDetailApi.js
- frontend/sellution-app/src/client/utility/functions/eventAddFunction.js
- frontend/sellution-app/src/client/utility/tableinfo/EventListTableInfo.js
- 고객 화면 이벤트 관련 페이지 API 연결
- 고객 목록 조회, 상세 조회, 수정, 삭제 API 연결
-  예외처리 및 필터링 확인 필요
> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요
*
* Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)
#
> [K1P-213] feat: 고객 화면 이벤트 목록조회, 상세조회, 등록, 수정, 삭제 API 연결

- backend/server/src/main/java/shop/sellution/server/event/application/EventServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/event/dto/request/SaveEventReq.java
- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- backend/server/src/main/java/shop/sellution/server/product/domain/ProductImageRepository.java
- frontend/sellution-app/src/shopping/business/layout/partials/useCoupon.js
- frontend/sellution-app/src/shopping/business/onetimeDelivery/useList.js
- frontend/sellution-app/src/shopping/business/subscriptionDelivery/useList.js
- frontend/sellution-app/src/shopping/component/home/EventComponent.jsx
- frontend/sellution-app/src/shopping/component/onetimeDelivery/DetailComponent.jsx
- frontend/sellution-app/src/shopping/component/onetimeDelivery/ListComponent.jsx
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/DetailComponent.jsx
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/ListComponent.jsx
- frontend/sellution-app/src/shopping/layout/DetailLayout.jsx
- frontend/sellution-app/src/shopping/layout/MenuCategoryHeaderNav.jsx
- frontend/sellution-app/src/shopping/layout/OrderListLayout.jsx
- frontend/sellution-app/src/shopping/layout/order/PaymentEstimation.jsx
- frontend/sellution-app/src/shopping/layout/partials/Category.jsx
- frontend/sellution-app/src/shopping/layout/partials/DetailOption.jsx
- BACK : 이벤트 예외처리 추가
- FRONT : 회원 쇼핑몰 화면 프론트 마무리
- 이벤트 타겟 관련 예외처리 추가
- 상품, 이벤트 더미데이터 추가 
- 카테고리에 전체 추가
- 가격에 포맷 적용
- 페이지네이션 무한스크롤
- 할인 안하는 상품 표시
- 품절 상품 표시, 비활성화
-  머지 시 CONFLICT 나면 불러주세요~
> [K1P-267, K1P-246] BACK - 이벤트 예외처리 추가, FRONT-회원 쇼핑몰 화면 프론트 보완

- backend/server/src/main/java/shop/sellution/server/order/dto/response/FindOrderRes.java
- backend/server/src/main/java/shop/sellution/server/payment/domain/repository/PaymentHistoryRepositoryCustomImpl.java
- backend/server/src/main/java/shop/sellution/server/payment/dto/request/FindPaymentHistoryCond.java
- backend/server/src/main/java/shop/sellution/server/payment/presentation/PaymentHistoryController.java
- backend/server/src/test/java/shop/sellution/server/account/application/AccountServiceImplTest.java
[K1P-244]
- 결제내역 조회 조건 수정 [생성일]
[K1P-244]: https://hyosung-kosa-team1.atlassian.net/browse/K1P-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [K1P-230] back - 결제내역 조회 조건 수정

- frontend/sellution-app/src/client/business/product/category/useCategoryAdd.js
- frontend/sellution-app/src/client/business/product/category/useCategoryList.js
- frontend/sellution-app/src/client/business/product/useProductAdd.js
- frontend/sellution-app/src/client/business/product/useProductDetail.js
- frontend/sellution-app/src/client/component/product/AddComponent.jsx
- frontend/sellution-app/src/client/component/product/DetailComponent.jsx
- frontend/sellution-app/src/client/component/product/category/AddComponent.jsx
- frontend/sellution-app/src/client/component/product/category/ListComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/IndexComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/address/AddComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/editSimplePassword/CheckSmsAuthComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/editSimplePassword/EditComponent.jsx
- frontend/sellution-app/src/shopping/component/mypage/payment/ListComponent.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/auth/SimplePasswordComponent.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/setting/address/AddComponent.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/setting/address/ListComponent.jsx
- frontend/sellution-app/src/shopping/layout/order/DeliverySelection.jsx
- frontend/sellution-app/src/shopping/layout/order/PaymentMethodSelection.jsx
- frontend/sellution-app/src/shopping/layout/order/SubscriptionDeliverySetting.jsx
- frontend/sellution-app/src/shopping/layout/partials/MyCoupon.jsx
- frontend/sellution-app/src/shopping/layout/partials/ReusableOneButtonModal.jsx
- frontend/sellution-app/src/shopping/layout/partials/ReusableTwoButtonModal.jsx
- frontend/sellution-app/src/shopping/layout/partials/TwoButtonModal.jsx
- flow 보면서 고쳐야할 부분들 수정
-  commit 안하고 pull 땡겨서 날라간 코드 다시 구현
> [K1P-127] client product

- .github/workflows/back-sollution-pg.yml
- .github/workflows/back-sollution.yml
- .github/workflows/front.yml
- backend/server/src/main/java/shop/sellution/server/scheduler/presentation/SchedulerTestController.java
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/test/TestController.java
[K1P-269]
- 인프라 테스트를 위한 main merge
[K1P-269]: https://hyosung-kosa-team1.atlassian.net/browse/K1P-269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [K1P-269] back - 인프라 테스트를 위한 main merge

- .github/workflows/pr.yml
- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
-  pr 올릴때 테스트 동작하도록 workflow파일 추가
> [K1P-216] 인프라 : pr 올릴때 테스트 동작하도록 수정

- backend/server/src/main/resources/static/docs/account.html
- backend/server/src/main/resources/static/docs/address.html
- backend/server/src/main/resources/static/docs/company.html
- backend/server/src/main/resources/static/docs/index.html
- backend/server/src/main/resources/static/docs/order.html
- backend/server/src/main/resources/static/docs/payment.html
- backend/server/src/main/resources/static/docs/product.html
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/payment/presentation/PaymentController.java
> [K1P-244] back - 결제시 아이피 검증로직 수정

- backend/server/src/docs/asciidoc/order.adoc
- backend/server/src/docs/asciidoc/product.adoc
- backend/server/src/main/java/shop/sellution/server/product/domain/Product.java
- backend/server/src/main/java/shop/sellution/server/product/domain/ProductRepository.java
- backend/server/src/main/java/shop/sellution/server/product/presentation/ProductController.java
- backend/server/src/main/java/shop/sellution/server/scheduler/application/SchedulerService.java
- backend/server/src/main/java/shop/sellution/server/scheduler/presentation/SchedulerTestController.java
- backend/server/src/main/resources/static/docs/account.html
- backend/server/src/main/resources/static/docs/index.html
- backend/server/src/main/resources/static/docs/order.html
- backend/server/src/main/resources/static/docs/payment.html
- backend/server/src/main/resources/static/docs/product.html
- backendPG/pgserver/src/main/resources/static/docs/account.html
- backendPG/pgserver/src/main/resources/static/docs/auth.html
- backendPG/pgserver/src/main/resources/static/docs/index.html
> [K1P-244] back - 상품조회 변경

- backend/server/src/main/java/shop/sellution/server/order/application/OrderService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/order/domain/repository/OrderRepository.java
- backend/server/src/main/java/shop/sellution/server/order/presentation/OrderController.java
> [K1P-244] back -  회사의 승인안된 주문건수 조회 API

- backend/server/src/main/java/shop/sellution/server/global/exception/ExceptionCode.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderServiceImpl.java
> [K1P-244] back - 주문시 해당 상품 공개여부 처리

- backend/server/src/main/java/shop/sellution/server/category/domain/CategoryRepository.java
- backend/server/src/main/java/shop/sellution/server/company/application/CompanySaleSettingServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/company/dto/FindCompanySaleSettingRes.java
- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
- backend/server/src/main/java/shop/sellution/server/product/domain/ProductRepository.java
- backend/server/src/main/java/shop/sellution/server/product/presentation/ProductController.java
- backend/server/src/test/java/shop/sellution/server/company/presentation/CompanyControllerTest.java
- frontend/sellution-app/src/client/business/product/useProductAdd.js
- frontend/sellution-app/src/client/business/product/useProductDetail.js
- frontend/sellution-app/src/client/business/product/useProductList.js
- frontend/sellution-app/src/client/component/product/AddComponent.jsx
- frontend/sellution-app/src/client/component/product/DetailComponent.jsx
- frontend/sellution-app/src/client/component/product/category/AddComponent.jsx
- frontend/sellution-app/src/client/component/product/category/DetailComponent.jsx
- frontend/sellution-app/src/client/component/product/category/ListComponent.jsx
- frontend/sellution-app/src/client/layout/common/table/TableProduct.jsx
> [K1P-127] chore, test : UI 개선, 테스트 코드 수정

- frontend/sellution-app/.env
- frontend/sellution-app/src/client/business/customer/detail/address/useCustomerAddressAdd.js
- frontend/sellution-app/src/client/business/customer/detail/address/useCustomerAddressDetail.js
- frontend/sellution-app/src/client/business/customer/detail/useCustomerDefault.js
- frontend/sellution-app/src/client/business/event/useEventAdd.js
- frontend/sellution-app/src/client/business/event/useEventDetail.js
- frontend/sellution-app/src/client/business/event/useEventList.js
- frontend/sellution-app/src/client/business/paymentHistory/usePaymentHistoryList.js
- frontend/sellution-app/src/client/business/shopManagement/useShopManagementDisplaySetting.js
- frontend/sellution-app/src/client/business/shopManagement/useShopManagementSaleSetting.js
- frontend/sellution-app/src/client/business/shopManagement/useShopManagementUrlSetting.js
- frontend/sellution-app/src/client/component/event/AddComponent.jsx
- frontend/sellution-app/src/client/component/event/ListComponent.jsx
- frontend/sellution-app/src/client/component/shopManagement/DisplaySettingComponent.jsx
- frontend/sellution-app/src/client/component/shopManagement/SaleSettingComponent.jsx
- frontend/sellution-app/src/client/layout/common/table/TableEvent.jsx
- frontend/sellution-app/src/client/utility/apis/event/eventDetailApi.js
- frontend/sellution-app/src/client/utility/apis/shopManagement/shopManagementDisplaySettingApi.js
- frontend/sellution-app/src/client/utility/apis/shopManagement/shopManagementSaleSettingApi.js
- 고객 화면 판매설정 조회 에러 수정 및 예외처리
- 로딩 지연에 대해 로딩창 구현
- 판매 설정 조회시 카테고리 및 상품 조회에 대한 에러 수정
-  코드테스트 에러, 수정 예정
> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요
*
* Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)
#
> Feature/k1 p 213 고객 화면 판매설정 조회 에러 수정 및 예외처리

- frontend/sellution-app/.env
- frontend/sellution-app/src/client/business/loading/useLoading.js
- frontend/sellution-app/src/client/business/shopManagement/useShopManagementDisplaySetting.js
- frontend/sellution-app/src/client/business/shopManagement/useShopManagementUrlSetting.js
- frontend/sellution-app/src/client/component/loading/LodingComponent.jsx
- frontend/sellution-app/src/client/page/loading/LoadingPage.jsx
- frontend/sellution-app/src/client/router/product/productRouter.jsx
- frontend/sellution-app/src/client/utility/assets/Icons.jsx
- frontend/sellution-app/src/shopping/utility/axios/Interceptors.js
- frontend/sellution-app/vite.config.js
- [] 기능 추가
- 고객 화면 navlink 수정
- 회원 프론트 interceptor 수정
- 고객 화면 loading 페이지 적용
- 고객 화면 navlink 수정
- 회원 프론트 interceptor 수정
- 고객 화면 loading 페이지 적용
- 
-  코드테스트 에러, 수정 예정
> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요
*
* Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)
#
> Feature/k1 p 213 고객 화면 navlink 수정, 회원 프론트 interceptor 수정, 고객 화면 loading 페이지 적용

- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentCancelService.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentService.java
- backend/server/src/main/java/shop/sellution/server/sms/application/SmsAuthNumberServiceImpl.java
> 테스트를 위한 문자 주석 해제

- backend/server/src/test/java/shop/sellution/server/order/application/OrderServiceImplTest.java
> [K1P-244] refactor: 주문취소 테스트코드 수정

- backend/server/.idea/compiler.xml
- backend/server/src/main/java/shop/sellution/server/account/infrastructure/AccountAuthService.java
- backend/server/src/main/java/shop/sellution/server/customer/domain/CustomerRepository.java
- backend/server/src/main/java/shop/sellution/server/event/application/EventServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/order/domain/Order.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentCancelService.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentService.java
- backend/server/src/main/java/shop/sellution/server/scheduler/application/SchedulerService.java
- backend/server/src/main/java/shop/sellution/server/sms/application/SmsAuthNumberServiceImpl.java
- frontend/sellution-app/.env
- frontend/sellution-app/src/client/business/order/useOrderDetail.js
- frontend/sellution-app/src/client/component/order/DetailComponent.jsx
- frontend/sellution-app/src/client/layout/order/PaymentInfo.jsx
- frontend/sellution-app/src/client/utility/functions/orderDetailFunction.js
- frontend/sellution-app/src/shopping/component/mypage/order/ListComponent.jsx
- frontend/sellution-app/src/shopping/component/onetimeDelivery/OrderCompletedComponent.jsx
- frontend/sellution-app/src/shopping/component/onetimeDelivery/OrderCompletedPaymentHistory.jsx
- frontend/sellution-app/src/shopping/component/ordersheet/auth/SimplePasswordComponent.jsx
> [K1P-244] back, front : 주문상세페이지 수정, 동시주문오류 해결

- backend/server/src/main/java/shop/sellution/server/global/BaseEntity.java
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/OrderCompletedPaymentHistory.jsx
> [K1P-244] back - 주문 생성시간 타임존 이슈 수정

- backend/server/src/main/java/shop/sellution/server/global/DataInitializer.java
- backend/server/src/main/resources/logback.xml
- backend/server/src/main/resources/static/docs/account.html
- backend/server/src/main/resources/static/docs/company.html
- backend/server/src/main/resources/static/docs/index.html
- backend/server/src/main/resources/static/docs/order.html
- backend/server/src/main/resources/static/docs/payment.html
- backend/server/src/main/resources/static/docs/product.html
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/account/infrastructure/AccountAuthService.java
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/account/infrastructure/IamPortTokenClient.java
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/auth/presentation/AuthController.java
- backendPG/pgserver/src/main/resources/logback.xml
> [K1P-244] back - 결제로깅 더 추가

- backend/server/src/test/java/shop/sellution/server/event/application/EventServiceImplTest.java
- 이벤트 동시성 처리 테스트
- QA 사항 반영 UI 개선
- 이벤트 동시성 처리 테스트
- QA 사항 반영 UI 개선
- 장바구니 예외처리 코드 추가
- 주문 결제금액 문제 수정
- 테스트 실패케이스 주석처리
> [K1P-268, K1P-246] test : 이벤트 동시성 처리 테스트 & 

- backend/server/src/docs/asciidoc/index.adoc
- backend/server/src/main/resources/static/docs/account.html
- backend/server/src/main/resources/static/docs/accountAuth.html
- backend/server/src/main/resources/static/docs/company.html
- backend/server/src/main/resources/static/docs/easyPwd.html
- backend/server/src/main/resources/static/docs/index.html
- backend/server/src/main/resources/static/docs/order.html
- backend/server/src/main/resources/static/docs/payment.html
- backend/server/src/main/resources/static/docs/product.html
- backendPG/pgserver/src/main/resources/static/docs/account.html
- backendPG/pgserver/src/main/resources/static/docs/auth.html
- backendPG/pgserver/src/main/resources/static/docs/index.html
> [K1P-244]  - RestDocs 정리

- backend/server/src/docs/asciidoc/cart.adoc
- backend/server/src/docs/asciidoc/category.adoc
- backend/server/src/docs/asciidoc/event.adoc
- backend/server/src/docs/asciidoc/index.adoc
- backend/server/src/docs/asciidoc/product.adoc
- backend/server/src/test/java/shop/sellution/server/cart/presentation/CartControllerTest.java
- backend/server/src/test/java/shop/sellution/server/category/presentation/CustomerCategoryControllerTest.java
- backend/server/src/test/java/shop/sellution/server/event/presentation/EventControllerTest.java
- backend/server/src/test/java/shop/sellution/server/product/presentation/CustomerProductControllerTest.java
- 구현 파트 전체 테스트 코드 작성 및 .adoc 작성
- customerProductController 테스트 코드 작성 및 .adoc 작성
- customerCategoryController 테스트 코드 작성 및 .adoc 작성
- eventController 테스트 코드 작성 및 .adoc 작성
- cartController 테스트 코드 작성 및 .adoc 작성
> [K1P-136 , K1P-125 , K1P-133 , K1P-40] test : 테스트 코드 및 .adoc 작성 완료

- backend/server/src/main/java/shop/sellution/server/account/infrastructure/AccountAuthService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/payment/infrastructure/PgTokenClient.java
- backend/server/src/main/java/shop/sellution/server/scheduler/application/SchedulerService.java
- backendPG/pgserver/src/main/java/pg/sellution/pgserver/account/infrastructure/AccountAuthService.java
- frontend/sellution-app/src/shopping/component/subscriptionDelivery/OrderCompletedComponent.jsx
> [K1P-244] back,front - 주문완료 페이지 색 변경, back 주석 지우기

- backend/server/.idea/compiler.xml
- backend/server/src/docs/asciidoc/client.adoc
- backend/server/src/docs/asciidoc/contractCompany.adoc
- backend/server/src/docs/asciidoc/customer.adoc
- backend/server/src/docs/asciidoc/index.adoc
- backend/server/src/main/resources/static/docs/account.html
- backend/server/src/main/resources/static/docs/accountAuth.html
- backend/server/src/main/resources/static/docs/address.html
- backend/server/src/main/resources/static/docs/client.html
- backend/server/src/main/resources/static/docs/company.html
- backend/server/src/main/resources/static/docs/contractCompany.html
- backend/server/src/main/resources/static/docs/customer.html
- backend/server/src/main/resources/static/docs/easyPwd.html
- backend/server/src/main/resources/static/docs/index.html
- backend/server/src/main/resources/static/docs/order.html
- backend/server/src/main/resources/static/docs/payment.html
- backend/server/src/main/resources/static/docs/product.html
- backend/server/src/test/java/shop/sellution/server/client/application/ClientServiceImplTest.java
- backend/server/src/test/java/shop/sellution/server/client/presentation/ClientControllerTest.java
- backend/server/src/test/java/shop/sellution/server/contractcompany/presentation/ContractCompanyControllerTest.java
- backend/server/src/test/java/shop/sellution/server/customer/presentation/CustomerControllerTest.java
- frontend/sellution-app/.env
- frontend/sellution-app/index.html
- frontend/sellution-app/public/sellution.svg
- frontend/sellution-app/src/client/business/order/useOrderList.js
- 파비콘 추가
- 테스트코드 작성
- 파일 수정
- 파비콘 추가
- 테스트코드 작성
- 파일 수정
-  코드테스트 에러, 수정 예정
> 개발 과정에서 다른 분들의 의견은 어떠한지 궁금했거나 크로스 체크가 필요하다고 느껴진 코드가 있다면 남겨주세요
*
* Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
* P1 : 꼭 반영해 주세요 (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
* P2 : 반영을 적극적으로 고려해 주시면 좋을 것 같아요 (Comment)
* P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 (Chore)
#
> [K1P-213] feat: 파비콘 추가 및 테스트 코드 작성

- frontend/sellution-app/src/client/utility/apis/order/orderListApi.js
> conflict 해결

- backend/server/src/main/java/shop/sellution/server/event/application/EventServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderCreationService.java
- backend/server/src/main/java/shop/sellution/server/order/application/OrderServiceImpl.java
- backend/server/src/main/java/shop/sellution/server/order/domain/repository/OrderRepositoryCustomImpl.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentCancelService.java
- backend/server/src/main/java/shop/sellution/server/payment/application/PaymentService.java
- backend/server/src/main/java/shop/sellution/server/payment/domain/repository/PaymentHistoryRepositoryCustomImpl.java
- backend/server/src/main/java/shop/sellution/server/scheduler/application/SchedulerService.java
- backend/server/src/main/java/shop/sellution/server/sms/application/SmsAuthNumberServiceImpl.java
> [K1P-244] 정렬순서변경
